### ISSUE TITLE
App crash when width/height are too bigger in encodeBarcode()

### ISSUE THREAD

**Issue by romgrm** [khoren93/flutter_zxing#100]
Hello :) 

I want to generate a barcode in aztec format. 
So I use the encodeBarcode() method, to which I send the data and set the parameters. 
The default width/height (120px) doesn't work for me, so I increase it. 

```dart
class BarcodeGeneratorService implements BarcodeGeneratorInterface {
  final Zxing _barcodeGenerator;

  BarcodeGeneratorService({Zxing? flutterZxing}) : _barcodeGenerator = flutterZxing ?? Zxing();
  @override
  Uint8List? encode({
    required String textToEncode,
    required int format,
    required int width,
    required int height,
    required int margin,
  }) {
    final encoded = _barcodeGenerator.encodeBarcode(
        contents: textToEncode,
        params: EncodeParams(format: Format.aztec,  width: 150, height: 150 , eccLevel: EccLevel.high));

    if (!encoded.isValid || encoded.data == null) {
      return null;
    }
    final imglib.Image img = imglib.Image.fromBytes(
      150,
      150,
      encoded.data!,
    );
    return Uint8List.fromList(
      imglib.encodeJpg(img),
    );
  }
}
```

When I want to display my barcode, when the encodeBarcode() method is triggered, my application crashes at this point. 

The crash occurs on several physical iOS devices, in 16 and 16.5. 
On the other hand, everything works fine on simulator. 

The error is not very clear: 

![image](https://github.com/khoren93/flutter_zxing/assets/72022928/841ed398-59e8-4500-981e-389b83258282)

Do you have any idea what it could be? 

Thanks :)

**Comment by PhenixZeller** [comment]
I got the same Problem when I try to encode a QR-Code. For me it works in the Debug build when I set the width&height to 128 in the Debug build, but on the release build the App crashes.

Luckily I have FirebaseCrashlytics configured.

Please take a look:

```dart
Fatal Exception: java.lang.IllegalArgumentException: CaptureRequest contains unconfigured Input/Output Surface!
       at android.hardware.camera2.CaptureRequest.convertSurfaceToStreamId(CaptureRequest.java:738)
       at android.hardware.camera2.impl.CameraDeviceImpl.submitCaptureRequest(CameraDeviceImpl.java:1187)
       at android.hardware.camera2.impl.CameraDeviceImpl.setRepeatingRequest(CameraDeviceImpl.java:1235)
       at android.hardware.camera2.impl.CameraCaptureSessionImpl.setRepeatingRequest(CameraCaptureSessionImpl.java:312)
       at z5.q.g0(:33)
       at z5.q$b.onConfigured(:41)
       at android.hardware.camera2.impl.CallbackProxies$SessionStateCallbackProxy.lambda$onConfigured$0$CallbackProxies$SessionStateCallbackProxy(CallbackProxies.java:53)
       at android.hardware.camera2.impl.-$$Lambda$CallbackProxies$SessionStateCallbackProxy$soW0qC12Osypoky6AfL3P2-TeDw.run(:4)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:923)
```
