### ISSUE TITLE
App Crashes: FATAL EXCEPTION: pool-109-thread-1 (java.lang.IllegalArgumentException: Each request must have at least one Surface target)

### ISSUE THREAD

**Issue by Venkat-polagani7** [khoren93/flutter_zxing#139]
Hello @khoren93,

I have an issue encountering recently in this package when uploading the images from the ReaderWidget. When I continuously uploads the images from the gallery consequently 10~15 times,  the app is being crashed and throwing the errors as shown below:

```
E/AndroidRuntime(13388): FATAL EXCEPTION: pool-109-thread-1
E/AndroidRuntime(13388): Process: com.example.projectCamera, PID: 13388
E/AndroidRuntime(13388): java.lang.IllegalArgumentException: Each request must have at least one Surface target
E/AndroidRuntime(13388): 	at android.hardware.camera2.impl.CameraDeviceImpl.submitCaptureRequest(CameraDeviceImpl.java:1293)
E/AndroidRuntime(13388): 	at android.hardware.camera2.impl.CameraDeviceImpl.setRepeatingRequest(CameraDeviceImpl.java:1369)
E/AndroidRuntime(13388): 	at android.hardware.camera2.impl.CameraCaptureSessionImpl.setRepeatingRequest(CameraCaptureSessionImpl.java:332)
E/AndroidRuntime(13388): 	at io.flutter.plugins.camera.Camera.refreshPreviewCaptureSession(Camera.java:587)
E/AndroidRuntime(13388): 	at io.flutter.plugins.camera.Camera$2.onConfigured(Camera.java:518)
E/AndroidRuntime(13388): 	at android.hardware.camera2.impl.CallbackProxies$SessionStateCallbackProxy.lambda$onConfigured$0(CallbackProxies.java:53)
E/AndroidRuntime(13388): 	at android.hardware.camera2.impl.CallbackProxies$SessionStateCallbackProxy.$r8$lambda$XOBHWVfryPuKTX27fDYaiDBtLvc(Unknown Source:0)
E/AndroidRuntime(13388): 	at android.hardware.camera2.impl.CallbackProxies$SessionStateCallbackProxy$$ExternalSyntheticLambda6.run(Unknown Source:4)
E/AndroidRuntime(13388): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
E/AndroidRuntime(13388): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
E/AndroidRuntime(13388): 	at java.lang.Thread.run(Thread.java:1012)
```

There was some information about this error in the CameraDeviceImp code, [here](https://android.googlesource.com/platform/frameworks/base/+/master/core/java/android/hardware/camera2/impl/CameraDeviceImpl.java#1261) is the link to it.
```

// Make sure that there all requests have at least 1 surface; all surfaces are non-null;
for (CaptureRequest request : requestList) {
   if (request.getTargets().isEmpty()) {
     throw new IllegalArgumentException(
     "Each request must have at least one Surface target");
   }
  
   for (Surface surface : request.getTargets()) {
     if (surface == null) {
         throw new IllegalArgumentException("Null Surface targets are not allowed");
     }
   }   
}
 
```
@khoren93 Could you please help me in resolving this issue ? or any suggestions to avoid this issue also appreciated.

Thanks

**Comment by khoren93** [comment]
This should be resolved as of 2.4.0.

Your stack trace is inside `io.flutter.plugins.camera.Camera` — the old **camera2** Android implementation of the `camera` plugin. That implementation was replaced by CameraX in `camera` 0.11.0, and this class of failure (unconfigured surfaces, sessions closed out from under a repeating request, null capture sessions) lives there, not in this plugin.

`flutter_zxing` allowed `camera: ">=0.10.5"`, so an old resolution could still pull in the camera2 implementation. 2.4.0 raises the floor to `camera: ">=0.11.0 <0.13.0"`, which is the release where Android moved to CameraX — so the code in your stack trace is no longer used at all.

If you are pinned to an older `flutter_zxing`, `flutter pub upgrade camera` on a recent Flutter achieves the same thing.

Closing — please reopen if you still see a crash inside `io.flutter.plugins.camera` on 2.4.0, since that would mean camera2 is somehow still being selected.
