### ISSUE TITLE
A CameraController was used after being disposed

### ISSUE THREAD

**Issue by LinHaoLove** [khoren93/flutter_zxing#23]
hi,sir,
On iOS,
Only after the first installation and permission, the following error will appear. When I try to use the cameracontroller to avoid this problem, I cannot refer to it.
However, this error did not affect the normal operation of the program , But the picture in the camera is shaking badly. It didn't happen yesterday, it often happens today

flutter: AppLifecycleState.resumed
[VERBOSE-2:ui_dart_state.cc(198)] Unhandled Exception: A CameraController was used after being disposed.
Once you have called dispose() on a CameraController, it can no longer be used.
#0      ChangeNotifier._debugAssertNotDisposed.<anonymous closure> (package:flutter/src/foundation/change_notifier.dart:125:9)
#1      ChangeNotifier._debugAssertNotDisposed (package:flutter/src/foundation/change_notifier.dart:131:6)
#2      ChangeNotifier.notifyListeners (package:flutter/src/foundation/change_notifier.dart:304:12)
#3      ValueNotifier.value= (package:flutter/src/foundation/change_notifier.dart:428:5)
#4      CameraController.setFlashMode (package:camera/src/camera_controller.dart:624:7)
<asynchronous suspension>
#5      _ReaderWidgetState.onNewCameraSelected (package:flutter_zxing/src/ui/reader_widget.dart:132:7)
<asynchronous suspension>

On Android,
I got seven warnings, I'm not sure if it's the reference of this plug-in. But I don't use the camera anywhere else.
After sudo rm -rf .pub-cache,it is ok.

like this
my_flutter_stable_sdk/flutter/.pub-cache/hosted/pub.flutter-io.cn/camera_android-0.10.0+1/android/src/main/java/io/flutter/plugins/camera/features/resolution/ResolutionFeature.java:154: 警告: [deprecation] CamcorderProfile中的get(int,int)已过时
          return CamcorderProfile.get(cameraId, CamcorderProfile.QUALITY_HIGH);

CamcorderProfile.QUALITY_2160P,
CamcorderProfile.QUALITY_1080P,
CamcorderProfile.QUALITY_720P,
CamcorderProfile.QUALITY_480P,
CamcorderProfile.QUALITY_QVGA
CamcorderProfile.QUALITY_LOW

**Comment by LinHaoLove** [comment]
Thank you for have a look.

PermissionStatus state = await Permission.camera.request();
                  if (state.isGranted==true){
                    pushViewController(context: context, child: const GatewayQrCodeWidgetScanner());
                  }else{
//Here's the hint
                  }
